AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD Pipeline for cognito-app-infra

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub Owner
  GitHubRepo:
    Type: String
    Description: GitHub Repository Name
  GitHubBranch:
    Type: String
    Description: GitHub Branch Name
  GitHubConnectionArn:
    Type: String
    Description: ARN of the GitHub connection in AWS Connector
  ProductionAccountId:
    Type: String
    Description: AWS Account ID for Production

Resources:
  CodeBuildProjectAccept:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: cognito-app-infra-deploy-accept
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/deploy/buildspec.yaml

  CodeBuildProjectProduction:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: cognito-app-infra-deploy-accept
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/deploy/buildspec.yaml

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: cognito-app-infra-pipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Sub '${GitHubOwner}/${GitHubRepo}'
                BranchName: !Ref GitHubBranch
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: Development
          Actions:
            - Name: DeployInDevelopment
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProjectAccept
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutputAccept
              RunOrder: 1
        - Name: Approval
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              RunOrder: 1
        - Name: Production
          Actions:
            - Name: DeployInProduction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProjectProduction
              InputArtifacts:
                - Name: BuildOutputAccept
              OutputArtifacts:
                - Name: BuildOutputAcceptProduction
              RunOrder: 1

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CognitoAppInfraCodeBuildServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      Policies:
        - PolicyName: CodeStarConnectionAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: !Ref GitHubConnectionArn

  PipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cognito-app-infra-pipeline-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled

Outputs:
  PipelineUrl:
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/codesuite/codepipeline/pipelines/${CodePipeline}/view?region=${AWS::Region}
    Description: CodePipeline URL
